"""Emit a theme's ``.mplstyle`` overlay from its :class:`~journalfig._specs.JournalSpec`.

Every number a theme renders with used to be written twice -- once in ``_specs.py``, where
:func:`journalfig.check` reads it, and once by hand in the stylesheet, where matplotlib reads it. The
two could disagree, and did. The overlays are now generated from the spec, so the stylesheet cannot say
something the checker will then flag.

Only what differs between journals is generated here; everything shared lives hand-written in
``styles/_base.mplstyle``. Comments in the output are derived rather than stored wherever the reasoning
follows from the numbers -- a marker size is explained in millimetres against the publisher's own
minimum -- so they cannot go stale the way a hand-written comment does.

Regenerate after any spec change::

    python -m journalfig._stylegen

Author: Achraf Atila (achraf.atila@bam.de)
"""

from __future__ import annotations

from pathlib import Path

from ._specs import GOLDEN, PT_PER_MM, SOURCES, SPECS, JournalSpec, mm_to_inch

_STYLE_DIR = Path(__file__).parent / "styles"

#: Column the values line up in, matching the hand-written base.
_COLUMN = 32

#: Written above every generated file so nobody edits the wrong end of the pipeline.
_BANNER = (
    "# GENERATED by journalfig._stylegen from SPECS -- do not edit.\n"
    "# Change the JournalSpec in _specs.py and run `python -m journalfig._stylegen`.\n"
    "# Shared settings live in _base.mplstyle, which is hand-written and applied first.\n"
)


def _line(key: str, value: object) -> str:
    """One ``key: value`` line, padded to the column the base file uses."""
    return f"{key + ':':<{_COLUMN}}{value}"


def _header(key: str, spec: JournalSpec) -> list[str]:
    """The provenance block: which document the numbers came from, and when it was read."""
    out = [_BANNER.rstrip("\n"), "#", f"# {spec.name} figure style"]
    source = SOURCES.get(key)
    if source is not None:
        out += [f"# Spec: {source.url}", f"#   {source.title}, retrieved {source.retrieved}"]

    widths = ", ".join(f"{name} {value:.4g} mm" for name, value in sorted(spec.widths_mm.items()))
    out.append(f"#   widths: {widths}")
    stated = [
        (f"text {spec.text_min_pt:.4g}-{spec.text_max_pt:.4g} pt" if spec.text_max_pt else None),
        (f"sub/superscripts >= {spec.sub_min_pt:.4g} pt" if spec.sub_min_pt else None),
        (f"lettering >= {spec.min_lettering_mm:.4g} mm" if spec.min_lettering_mm else None),
        (f"data points >= {spec.min_marker_mm:.4g} mm" if spec.min_marker_mm else None),
        (f"lines >= {spec.min_linewidth_pt:.4g} pt" if spec.min_linewidth_pt else None),
        (f"raster >= {spec.raster_dpi} dpi" if spec.raster_dpi else None),
    ]
    # IEEE states no minimum of any kind, so this line would otherwise be a bare "#   " -- trailing
    # whitespace that the pre-commit hook strips, leaving the committed file unequal to the generator.
    summary = "; ".join(item for item in stated if item)
    if summary:
        out.append(f"#   {summary}")
    for note in spec.notes:
        out += ["#"] + [f"# {line}" for line in note.splitlines()]
    return out


def _font_block(spec: JournalSpec) -> list[str]:
    """Family, stack and maths faces. The maths faces follow the stack's first entry."""
    style = spec.style
    out = [
        _line("font.family", style.font_family_category),
        _line(f"font.{style.font_family_category}", ", ".join(style.font_stack)),
        _line("font.size", f"{spec.font_sizes['base']:.4g}"),
        "",
        _line("mathtext.fontset", style.mathtext_fontset),
    ]
    if style.mathtext_fontset == "custom":
        face = style.font_stack[0]
        out += [
            _line("mathtext.rm", face),
            _line("mathtext.it", f"{face}:italic"),
            _line("mathtext.bf", f"{face}:bold"),
            _line("mathtext.sf", face),
            _line("mathtext.tt", "Courier New"),
        ]
    return out


def _marker_comment(spec: JournalSpec) -> list[str]:
    """Explain the marker size in printed millimetres, against the publisher's floor if it states one."""
    printed = spec.style.marker_size / PT_PER_MM
    if spec.min_marker_mm is None:
        return [f"# markersize {spec.style.marker_size:.4g} pt = {printed:.2f} mm printed."]
    return [
        f"# markersize {spec.style.marker_size:.4g} pt = {printed:.2f} mm printed, "
        f"clearing the {spec.min_marker_mm:.4g} mm data-point rule."
    ]


def overlay_text(key: str) -> str:
    """Return the full text of one theme's generated ``.mplstyle`` overlay.

    Args:
        key: A theme key from :data:`journalfig.SPECS`.

    Returns:
        The file contents, ending in a newline.

    Example:
        >>> text = overlay_text("nature")
        >>> text.splitlines()[0]
        '# GENERATED by journalfig._stylegen from SPECS -- do not edit.'
        >>> "font.size" in text
        True
    """
    spec = SPECS[key]
    style = spec.style
    sizes = spec.font_sizes
    width_in = mm_to_inch(spec.widths_mm["single"])

    out = _header(key, spec)
    out += [
        "",
        "# Single column at the inverse golden ratio, the same default journalfig.figsize() applies, so a",
        '# bare plt.subplots() here and jf.subplots(..., width="single") agree.',
        _line("figure.figsize", f"{width_in:.6f}, {width_in * GOLDEN:.6f}"),
        _line("figure.titlesize", f"{sizes['title']:.4g}"),
        "",
    ]
    out += _font_block(spec)
    out += [
        "",
        _line("axes.linewidth", f"{style.axes_linewidth:.4g}"),
        _line("axes.labelsize", f"{sizes['label']:.4g}"),
        _line("axes.titlesize", f"{sizes['title']:.4g}"),
        _line("axes.titleweight", style.title_weight),
        _line("axes.titlelocation", style.title_location),
        "",
    ]
    for axis in ("xtick", "ytick"):
        out += [
            _line(f"{axis}.labelsize", f"{sizes['tick']:.4g}"),
            _line(f"{axis}.major.size", f"{style.tick_major_size:.4g}"),
            _line(f"{axis}.major.width", f"{style.tick_major_width:.4g}"),
            _line(f"{axis}.major.pad", f"{style.tick_pad:.4g}"),
            _line(f"{axis}.minor.size", f"{style.tick_minor_size:.4g}"),
            _line(f"{axis}.minor.width", f"{style.tick_minor_width:.4g}"),
            "",
        ]
    out += _marker_comment(spec)
    out += [
        _line("lines.markersize", f"{style.marker_size:.4g}"),
        _line("lines.markeredgewidth", f"{style.marker_edge_width:.4g}"),
        "",
        _line("patch.linewidth", f"{style.axes_linewidth:.4g}"),
        _line("hatch.linewidth", f"{style.axes_linewidth:.4g}"),
        _line("grid.linewidth", f"{style.grid_linewidth:.4g}"),
        _line("errorbar.capsize", f"{style.errorbar_capsize:.4g}"),
        "",
        _line("legend.fontsize", f"{sizes['legend']:.4g}"),
        _line("legend.title_fontsize", f"{sizes['legend']:.4g}"),
        _line("legend.handlelength", f"{style.legend_handlelength:.4g}"),
    ]
    # _base.mplstyle already sets 600, which clears every floor stated so far. A publisher asking for
    # more -- Elsevier's 1000 dpi line art, say -- overrides it here rather than raising it for everyone.
    if spec.raster_dpi is not None and spec.raster_dpi > 600:
        out += [
            "",
            f"# {spec.name} states a floor above the 600 dpi shared default.",
            _line("savefig.dpi", spec.raster_dpi),
        ]
    return "\n".join(out) + "\n"


def write_all() -> list[Path]:
    """Regenerate every theme's overlay in place.

    Returns:
        The paths written, in theme order.

    Example:
        >>> written = write_all()
        >>> len(written) == len(SPECS) and all(p.suffix == ".mplstyle" for p in written)
        True
    """
    written = []
    for key in SPECS:
        path = _STYLE_DIR / f"{key}.mplstyle"
        path.write_text(overlay_text(key))
        written.append(path)
    return written


if __name__ == "__main__":
    for written_path in write_all():
        print(f"wrote {written_path}")
